---
title: "Analysis of the rent and income Datasets"
author: "Sonisa Sharma"
date: "9.11.2019"
output:
  ioslides_presentation
runtime: shiny
---

## Coursera Reproducible Pitch


This shinyapp includes income along with the expenditures on water, gas, electricity and rent.

[Link to github repo](https://github.com/sonisa/Week4DevelopingDataProducts)
[This is my shiny link](https://sonisa56.shinyapps.io/Week4Developingdataproducts_Sharma/#5)

---

```{r, echo=FALSE}
library(shiny)
library(shinydashboard)
library(rsconnect)
server<-shinyServer(
  function(input, output){
    output$rentalYield <- renderText({ calculateRentalYield(input$MonthlyRent, input$Income) })
    output$cashflowPerYear <- renderText({calculateYearlyCashflow(input$MonthlyRent, input$waterPerMonth, input$MonthlyGas, input$Electricity)})
    output$CashSavingYear <- renderText({CashSavingYear(input$MonthlyRent, input$waterPerMonth, input$MonthlyGas, input$Electricity)})
  }
)
calculateRentalYield <- function (MonthlyRent, Income) 
{
  result <- MonthlyRent * 12 / Income * 100
  return(round(result, digits = 2))
}

calculateYearlyCashflow <- function(MonthlyRent, MonthlyGas, waterpermonth, Electricity)
{
  result <- (MonthlyRent  + waterpermonth + MonthlyGas + Electricity )* 12
  return(result)
}
```

---
```{r ui,echo = TRUE}
ui<-shinyUI(pageWithSidebar(
  headerPanel("Investment Property"),
  sidebarPanel(
    h4('Property'),
    textInput('text', 'Address', value=''),
    numericInput('Income', 'Income ($)', 90000),
    numericInput('MonthlyRent', 'Monthly Rent ($)', 750),
    h5('Costs'),
    numericInput('MonthlyGas', 'MonthlyGas ($ per month)', 20),
    numericInput('waterPerMonth', 'Water ($ per month)', 60),
    numericInput('Electricity', 'Electricity ($ per month)', 100)
  ),
  mainPanel(
    h4('Rental Yield (%)'),
    textOutput("rentalYield"),
    h4('Cashflow Per Year ($)'),
    textOutput("cashflowPerYear")
  )
))
```
---
```{r, echo=TRUE}
shinyApp(ui = ui, server = server)
```

